skills = [{
    'id': 1,
    'name': 'Java'
    }, {
    'id': 2,
    'name': 'JavaScript'
    }, {
    'id': 3,
    'name': 'PHP'
    }, {
    'id': 4,
    'name': 'ReactJS'
    }, {
    'id': 5,
    'name': 'NodeJS'
    }, {
    'id': 6,
    'name': 'mySql'
    }, {
    'id': 7,
    'name': 'PostgreSQL'
    }, {
    'id': 8,
    'name': 'Python'
    }, {
    'id': 9,
    'name': 'Mongodb'
    }, {
    'id': 10,
    'name': 'CSS'
    }, {
    'id': 11,
    'name': 'HTML'
    }, {
    'id': 12,
    'name': 'Adobe'
    }, {
    'id': 13,
    'name': 'Photoshop'
    }, {
    'id': 14,
    'name': 'Microsoft Office'
    }]
